CREATE DATABASE IF NOT EXISTS `playlist`;
USE `playlist`;
DROP TABLE IF EXISTS `playlists`;
CREATE TABLE `playlists` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) CHARACTER SET hp8 COLLATE hp8_bin NOT NULL,
  `image` varchar(1000) CHARACTER SET hp8 COLLATE hp8_bin NOT NULL,
  `songs` text CHARACTER SET hp8 COLLATE hp8_bin NOT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- Dumping data for table `playlists`
--

INSERT INTO `playlists` (`id`, `name`, `image`, `songs`) VALUES
(16, 'Afro Lady', 'https://upload.wikimedia.org/wikipedia/en/5/50/Minnie_Riperton_Perfect_Angel.jpg', '[{\"name\":\"cfro\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Rococo_Var_orch.mp3\"},{\"name\":\"dfro\",\"url\":\"http:\\/\\/www.noiseaddicts.com\\/samples_1w72b820\\/4158.mp3\"},{\"name\":\"efro\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Rococo_Var_orch.mp3\"},{\"name\":\"ffro\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"hfrp\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"ifro\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Rococo_Var_orch.mp3\"},{\"name\":\"jfro\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"kfro\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Rococo_Var_orch.mp3\"},{\"name\":\"lfro\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"mfro\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"}]'),
(22, 'lamb is lamb ', 'https://upload.wikimedia.org/wikipedia/en/6/69/Infinityonhigh.jpg', '[{\"name\":\"lamb1\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Cello_Concerto_D-1.mp3\"},{\"name\":\"lamb2\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Rococo_Var_orch.mp3\"},{\"name\":\"lamb3\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Vivaldi_Sonata_eminor_.mp3\"},{\"name\":\"lamb4\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"},{\"name\":\"lamb5\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"lamb6\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"},{\"name\":\"lamb7\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"}]'),
(24, 'Best Classic Album', 'https://img.discogs.com/jDx0lSx9WaGzv3eaYW17aiWmJ3Y=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-10079449-1491241201-5695.png.jpg', '[{\"name\":\"TCHAIKOVSKY\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Rococo_Var_orch.mp3\"},{\"name\":\"VIVALDI\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Vivaldi_Sonata_eminor_.mp3\"},{\"name\":\"BEETHOVEN\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Beethoven_12_Variation.mp3\"},{\"name\":\"AVI BITTER\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Rococo_Var_orch.mp3\"}]'),
(28, 'Will Smith Hits    ', 'https://upload.wikimedia.org/wikipedia/en/5/59/Lostandfound.jpg', '[{\"name\":\"los angeles\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Rococo_Var_orch.mp3\"},{\"name\":\"Rehovot\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"Yavne\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Boccherini_Concerto_478-1.mp3\"},{\"name\":\"Rishon\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Beethoven_12_Variation.mp3\"},{\"name\":\"Gedera\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Boccherini_Concerto_478-1.mp3\"},{\"name\":\"Holon\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Rococo_Var_orch.mp3\"},{\"name\":\"Hadera\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Boccherini_Concerto_478-1.mp3\"}]'),
(91, 'Air Plane', 'https://pmcvariety.files.wordpress.com/2018/08/album-cover.jpg?w=1000&h=562&crop=1', '[{\"name\":\"AP 1\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"AP 2\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"}]'),
(92, 'Red Yellow', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrlTCZaje-tLP14QjI_jctWwKUqzhmCohMh5UAJrJFW3YSS3TvGw', '[{\"name\":\"ry1\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"ry2\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"ry3\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"ry4\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"}]'),
(93, 'Cubessss', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRwWQb8GKVp0N423enzyg4OaPrtpuFp2aU6obbFlTjWdAXo4Jy', '[{\"name\":\"Cube1\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"Cube2\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"Cube3\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"Cube4\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"}]'),
(94, 'SuoundGarden', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwxXbkaGKq1zEnGZ3_RuiInizdt-3AwjxWm6Op75c7d9IG0nVEkA', '[{\"name\":\"SG1\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"SG2\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"SG3\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"SG4\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"}]'),
(95, 'BIG FACE', 'https://www.billboard.com/files/styles/900_wide/public/media/Miles-Davis-Bitches-Brew-album-covers-billboard-1000x1000.jpg', '[{\"name\":\"FACE1\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"},{\"name\":\"FACE2\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"}]'),
(96, 'Party Monster', 'https://t2.genius.com/unsafe/523x0/https%3A%2F%2Fimages.genius.com%2F4d6ffe3578dd8517c3bf89bda373bc65.600x600x1.jpg', '[{\"name\":\"PM1\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"},{\"name\":\"PM2\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"}]'),
(98, 'Pretty', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2LRC6lEuo-Iv0cKKBYhxz1sAxHSR2N9W1GqMM_iWVYRMClJMa', '[{\"name\":\"pr1\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"},{\"name\":\"pr2\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"}]'),
(99, 'boston', 'https://cdn.theatlantic.com/assets/media/img/mt/2015/03/Boston/lead_720_405.jpg?mod=1533691735', '[{\"name\":\"BOSton1\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"},{\"name\":\"BOSto2\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"}]'),
(101, 'vfbgbnh', 'http://media.musicfeeds.com.au/files/265c269f23691e4d41881f95c3033bbf.jpg', '[{\"name\":\"AAA11\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"},{\"name\":\"bbbb2222\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"},{\"name\":\"ccccc33333\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"}]'),
(102, 'Kisssss', 'http://myspiltmilk.com/sites/default/files/main-image/cover_destroyer.jpg', '[{\"name\":\"Kisss1\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"}]'),
(108, 'RollingStons', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj94FxtTaPW10j-nfYEY8H9gOIfiTUHiLHPJK-P_yYRXJWWzdWEQ', '[{\"name\":\"RollingStons11\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"},{\"name\":\"RollingStons1122\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Tchaikovsky_Nocturne__orch.mp3\"}]'),
(109, 'Diamonds', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhs7hpGpywW5QWNEZsZF8eo6YcjPjwROaUlD7mCWE4yW0YdJ9g', '[{\"name\":\"Diamond111\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Beethoven_12_Variation.mp3\"},{\"name\":\"Diamond11122\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Beethoven_12_Variation.mp3\"},{\"name\":\"Diamond111233\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Beethoven_12_Variation.mp3\"}]'),
(110, 'American Idiot', 'https://www.billboard.com/files/styles/900_wide/public/media/Green-Day-American-Idiot-album-covers-billboard-1000x1000.jpg', '[{\"name\":\"American Idiot\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"},{\"name\":\"American Idiot 22\",\"url\":\"http:\\/\\/www.hochmuth.com\\/mp3\\/Haydn_Adagio.mp3\"}]');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
